# Generated by Django 4.2.21 on 2025-07-06 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='year',
            field=models.IntegerField(blank=True, default=2025, null=True, validators=[django.core.validators.MinValueValidator(1837), django.core.validators.MaxValueValidator(2025)], verbose_name='Year'),
        ),
    ]
