# Generated by Django 4.2.21 on 2025-07-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_active',
            new_name='active',
        ),
    ]
