# Generated by Django 4.2.21 on 2025-07-11 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_timestamp_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 11, 6, 19, 24, 711920, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 11, 6, 19, 24, 710886, tzinfo=datetime.timezone.utc)),
        ),
    ]
