# Generated by Django 4.2.21 on 2025-07-11 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_bid_timestamp_alter_listing_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 11, 7, 34, 57, 542988, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 11, 7, 34, 57, 542988, tzinfo=datetime.timezone.utc)),
        ),
    ]
